extends RefCounted

const DEFAULT_LOCALE := "en"
const SUPPORTED_LOCALES := ["en", "fr"]

const EN := {
	"tab.character": "Character",
	"tab.camp": "Camp",
	"tab.missions": "Missions",
	"tab.grimoire": "Grimoire",
	"tab.social": "Social",
	"tab.dungeon": "Dungeon",
	"tab.shop": "Shop",
	"tab.options": "Options",
	"vital.health": "HEALTH",
	"vital.endurance": "ENDURANCE",
	"vital.level": "LEVEL %d",
	"inventory.title": "INVENTORY",
	"option.language": "LANGUAGE",
	"option.english": "ENGLISH",
	"option.french": "FRENCH",
	"option.audio": "AUDIO",
	"option.music": "MUSIC",
	"option.sfx": "SFX",
	"option.sound_on": "SOUND: ON",
	"option.sound_off": "SOUND: OFF",
	"option.debug_on": "Debug mode: ON",
	"option.debug_off": "Debug mode: OFF",
	"placeholder.dungeon_title": "DUNGEON",
	"placeholder.dungeon_safe": "Safety mode active. The full dungeon panel is temporarily disabled to isolate the crash.",
	"mission.daily_timer": "Daily %s",
	"mission.weekly_timer": "Weekly %s",
	"mission.daily_section": "DAILY MISSIONS",
	"mission.weekly_section": "WEEKLY MISSION",
	"mission.exhausted": "Missions depleted.",
	"mission.no_weekly": "No challenge this week.",
	"mission.not_found": "MISSION NOT FOUND",
	"mission.journal": "Journal",
	"mission.journal_only_cap": "Journal only: daily limit reached",
	"mission.missing": "Missing: %s",
	"mission.blocked": "LOCKED",
	"mission.launch": "START - %d END",
	"mission.note_placeholder": "Short note",
	"mission.ready": "Ready to validate",
	"mission.remaining": "Remaining: %s",
	"mission.validate": "VALIDATE",
	"mission.abandon": "ABANDON",
	"mission.locked": "LOCKED",
	"mission.validation": "Validation: %s",
	"mission.validation_note": "note",
	"mission.validation_status_ready": "Ready",
	"mission.validation_status_wait": "In progress",
	"mission.blocker.not_found": "Mission not found",
	"mission.blocker.not_started": "Mission not started",
	"mission.blocker.time": "Time %s/%s",
	"mission.blocker.objective": "Objective %d/%d %s",
	"mission.blocker.note": "Note required",
	"mission.daily_quests": "Daily quests %d/%d",
	"mission.history": "Streak %dd | OK %d | KO %d",
	"journal.today": "Today: %d OK / %d KO",
	"journal.empty": "No completed mission yet.",
	"popup.level": "Level %d",
	"popup.stat_points": "+ 3 Stat Points available!",
	"popup.close": "CLOSE",
	"popup.continue": "CONTINUE",
	"popup.understood": "OK",
	"popup.mission_complete": "MISSION COMPLETE!",
	"popup.mission_failed": "MISSION FAILED",
	"popup.mission_injury": "You were injured during your mission.",
	"popup.journal_only": "Journal only",
	"popup.daily_limit": "Daily limit reached",
	"popup.rename": "CHANGE NAME",
	"popup.name_placeholder": "Your name...",
	"popup.cancel": "CANCEL",
	"popup.confirm": "CONFIRM",
	"item.power": "Power: %d",
	"item.no_bonus": "No bonus",
	"item.type.weapon": "Weapon",
	"item.type.armor": "Armor",
	"item.type.legs": "Legs",
	"item.type.feet": "Feet",
	"item.type.accessory": "Accessory",
	"item.rarity.common": "Common",
	"item.rarity.rare": "Rare",
	"item.rarity.epic": "Epic",
	"item.rarity.legendary": "Legendary",
	"item.rarity.mythic": "Mythic",
	"dungeon.rank_title": "%s - Rank %s",
	"dungeon.floor_status": "Floor %d / %d - %s",
	"dungeon.dead": "Expelled from the dungeon. Recover before trying again.",
	"dungeon.completed": "Dungeon complete. You can restart from the last checkpoint.",
	"dungeon.entry_cost": "Entry cost: %d END. The dungeon uses your current rank and stats.",
	"dungeon.checkpoint": "Checkpoint: floor %d | Best floor: %d | HP %d/%d | END %d/%d",
	"dungeon.floor_clear": "Floor cleared.",
	"dungeon.no_enemy": "No enemy.",
	"dungeon.loot": "LOOT %s",
	"dungeon.energy": "Energy: %d / 100",
	"dungeon.enter": "Enter (%d END)",
	"dungeon.auto": "Auto exchange",
	"dungeon.special": "Special attack",
	"dungeon.heal": "Heal",
	"dungeon.shield": "Shield",
	"dungeon.next": "Climb to next floor",
	"dungeon.leave": "Leave dungeon",
	"dungeon.phase.combat": "Combat",
	"dungeon.phase.event": "Event",
	"dungeon.phase.clear": "Floor cleared",
	"dungeon.phase.dead": "Defeat",
	"dungeon.phase.completed": "Complete",
	"dungeon.phase.idle": "Rest",
	"time.day_short": "d",
	"mission.validation_time": "Time %s/%s",
	"mission.validation_objective": "Objective %s",
	"mission.validation_free": "Free validation",
	"mission.amount_label.actions": "actions",
	"mission.amount_label.reps": "reps",
	"mission.amount_label.pas": "steps",
	"mission.amount_label.pages": "pages",
	"mission.amount_label.km": "km",
	"popup.level_up": "LEVEL UP!",
	"item.action.sell": "SELL  %d GOLD",
	"item.action.equip": "EQUIP",
	"item.action.unequip": "UNEQUIP",
	"tooltip.rename": "Rename",
	"debug.reset_daily": "Reset Daily",
	"debug.reset_weekly": "Reset Weekly",
	"debug.level_up": "+ Level",
	"debug.loot": "+ Loot",
	"debug.invincible_on": "Invincible: ON",
	"debug.invincible_off": "Invincible: OFF",
	"bestiary.monster.bat": "Bat",
	"bestiary.monster.mimic": "Mimic",
	"bestiary.monster.rat": "Rat",
	"bestiary.monster.slime": "Slime",
	"bestiary.monster.flying_eye": "Flying Eye",
	"bestiary.monster.goblin": "Goblin",
	"bestiary.monster.mushroom": "Mushroom",
	"bestiary.monster.skeleton": "Skeleton",
	"bestiary.monster.rat_savage": "Savage Rat",
	"bestiary.monster.golem_blue": "Blue Golem",
	"bestiary.monster.golem_orange": "Orange Golem",
	"bestiary.monster.demon_sword": "Demon Sword",
	"bestiary.monster.minotaur": "Minotaur",
	"bestiary.monster.demon_slime": "Demon Slime",
	"bestiary.monster.knight": "Knight",
	"bestiary.view_large": "View large",
	"dungeon.name.f": "Splitwood",
	"dungeon.name.e": "Rust Caves",
	"dungeon.name.d": "Hungry Crypts",
	"dungeon.name.c": "Echo Tower",
	"dungeon.name.b": "Kings' Pit",
	"dungeon.name.a": "Black Citadel",
	"dungeon.name.s": "Final Abyss",
	"dungeon.unavailable_rank": "Rank unavailable.",
	"dungeon.not_enough_end": "Not enough END to enter.",
	"dungeon.not_enough_hp": "Not enough HP to enter.",
	"dungeon.enter_log": "Entered %s. Checkpoint floor %d.",
	"dungeon.log.special": "Special attack: -%d enemy HP.",
	"dungeon.log.heal": "Heal: +%d HP.",
	"dungeon.log.shield": "Shield active for 2 exchanges.",
	"dungeon.log.altar_hp": "Altar: -%d HP, temporary ATK increased.",
	"dungeon.log.altar_end": "Altar: -%d END, temporary DEF increased.",
	"dungeon.log.altar_ignore": "You ignore the altar.",
	"dungeon.log.merchant_buy": "Merchant: potion received, +%d HP.",
	"dungeon.log.pass": "You move on.",
	"dungeon.log.test_success": "%s test succeeded. Energy +25.",
	"dungeon.log.test_fail": "%s test failed. Trap: -%d HP.",
	"dungeon.log.short_path": "Short path: -%d HP, one floor gained.",
	"dungeon.log.long_path": "Long path: temporary DEF +2.",
	"dungeon.log.leave": "Left the dungeon. Back to checkpoint.",
	"dungeon.log.spawn": "Floor %d: %s appears.",
	"dungeon.log.crit": "Critical hit: -%d enemy HP.",
	"dungeon.log.player_hit": "You strike: -%d enemy HP.",
	"dungeon.log.enemy_hit": "%s attacks: -%d HP.",
	"dungeon.log.checkpoint": "Checkpoint reached: floor %d.",
	"dungeon.log.floor_clear": "Floor %d cleared. You can climb.",
	"dungeon.log.event": "Event: %s.",
	"dungeon.log.complete": "%s complete. The 100 floors are conquered.",
	"dungeon.log.defeat": "Defeat. Back to checkpoint floor %d.",
	"dungeon.log.loot": "Loot obtained: %s.",
	"dungeon.inventory_full": "Inventory full. Loot lost.",
	"dungeon.enemy_type.Brute": "Brute",
	"dungeon.enemy_type.Assassin": "Assassin",
	"dungeon.enemy_type.Mage": "Mage",
	"dungeon.enemy_base.0.0": "Cave Rat",
	"dungeon.enemy_base.0.1": "Stray Dog",
	"dungeon.enemy_base.0.2": "Thin Bandit",
	"dungeon.enemy_base.1.0": "Rust Ghoul",
	"dungeon.enemy_base.1.1": "Bone Thief",
	"dungeon.enemy_base.1.2": "Soot Mage",
	"dungeon.enemy_base.2.0": "Hollow Sentinel",
	"dungeon.enemy_base.2.1": "Quick Shadow",
	"dungeon.enemy_base.2.2": "Cultist",
	"dungeon.enemy_base.3.0": "Split Knight",
	"dungeon.enemy_base.3.1": "Silent Blade",
	"dungeon.enemy_base.3.2": "Dry Oracle",
	"dungeon.enemy_base.4.0": "Pit Giant",
	"dungeon.enemy_base.4.1": "Royal Stalker",
	"dungeon.enemy_base.4.2": "Blood Mage",
	"dungeon.enemy_base.5.0": "Black Champion",
	"dungeon.enemy_base.5.1": "Elite Assassin",
	"dungeon.enemy_base.5.2": "Broken Archmage",
	"dungeon.enemy_base.6.0": "Abyss Avatar",
	"dungeon.enemy_base.6.1": "Void Hand",
	"dungeon.enemy_base.6.2": "Final Prophet",
	"dungeon.event.altar.title": "Cracked Altar",
	"dungeon.event.altar.text": "A cold stone demands a price before the next floor.",
	"dungeon.event.altar.choice_hp": "Sacrifice HP for ATK",
	"dungeon.event.altar.choice_end": "Sacrifice END for DEF",
	"dungeon.event.altar.choice_ignore": "Ignore",
	"dungeon.event.merchant.title": "Hidden Merchant",
	"dungeon.event.merchant.text": "A silhouette offers a potion for 8 END.",
	"dungeon.event.merchant.choice_buy": "Buy the potion",
	"dungeon.event.merchant.choice_pass": "Pass",
	"dungeon.event.trap.title": "Trapped Corridor",
	"dungeon.event.trap.text": "The floor cracks. Act fast or read the mechanism.",
	"dungeon.event.trap.choice_agi": "Dodge with AGI",
	"dungeon.event.trap.choice_int": "Analyze with INT",
	"dungeon.event.dilemma.title": "Two Paths",
	"dungeon.event.dilemma.text": "A dangerous shortcut drops through the rock. The other way is slower.",
	"dungeon.event.dilemma.choice_short": "Short path",
	"dungeon.event.dilemma.choice_long": "Long path",
	"item_data.massue.name": "Mace",
	"item_data.chemise_delavee.name": "Common Shirt",
	"item_data.short_de_timp.name": "Common Pants",
	"item_data.claquettes_de_boloss.name": "Common Slides",
	"item_data.poing_americain.name": "Brass Knuckles",
	"item_data.arbalete_en_bois.name": "Wooden Crossbow",
	"item_data.arc_en_bois.name": "Wooden Bow",
	"item_data.dague_en_fer.name": "Iron Dagger",
	"item_data.epee_en_bois.name": "Wooden Sword",
	"item_data.epee_en_fer.name": "Iron Sword",
	"item_data.fleau.name": "Flail",
	"item_data.hache_en_fer.name": "Iron Axe",
	"item_data.lance_en_fer.name": "Iron Spear",
	"mission_data.a_12km.title": "Unending Breath",
	"mission_data.a_12km.description": "Run 12 km.",
	"mission_data.a_90min.title": "Overloaded Body",
	"mission_data.a_90min.description": "Do 90 minutes of continuous physical activity.",
	"mission_data.a_cardio.title": "Cardio",
	"mission_data.a_cardio.description": "Do 1 hour of continuous effort.",
	"mission_data.a_competence.title": "Battle Calculation",
	"mission_data.a_competence.description": "Learn an advanced skill for 2 hours.",
	"mission_data.a_controle.title": "Control",
	"mission_data.a_controle.description": "Do an advanced mobility or balance session.",
	"mission_data.a_defi_repousse.title": "Predator's Will",
	"mission_data.a_defi_repousse.description": "Do a difficult activity you have been postponing.",
	"mission_data.a_hebdo_elite.title": "Elite Body",
	"mission_data.a_hebdo_elite.description": "Complete a triathlon: swimming, cycling and running in the same day.",
	"mission_data.a_hebdo_maitrise.title": "Body Mastery",
	"mission_data.a_hebdo_maitrise.description": "Hold a complex balance posture, such as a handstand.",
	"mission_data.a_intensif_1h.title": "Broken Limiter",
	"mission_data.a_intensif_1h.description": "Do an intense 1-hour workout.",
	"mission_data.a_leadership.title": "Dominant Presence",
	"mission_data.a_leadership.description": "Lead a project or a team for one day.",
	"mission_data.a_meditation.title": "Empty Mind",
	"mission_data.a_meditation.description": "Meditate for 45 minutes with total focus, without guidance or music.",
	"mission_data.a_puissance.title": "Power",
	"mission_data.a_puissance.description": "Do a high-intensity workout.",
	"mission_data.a_rigueur.title": "Rigor",
	"mission_data.a_rigueur.description": "Be up before 7:30.",
	"mission_data.a_silence.title": "Sixth Sense",
	"mission_data.a_silence.description": "Spend a full day without music or digital distraction.",
	"mission_data.a_souffle.title": "Breath",
	"mission_data.a_souffle.description": "Complete 3 heart-coherence breathing sessions.",
	"mission_data.a_sprint_agilite.title": "Ultimate Reaction",
	"mission_data.a_sprint_agilite.description": "Do an explosive workout combining sprinting and agility.",
	"mission_data.b_150_pompes.title": "Confirmed Player",
	"mission_data.b_150_pompes.description": "Complete 150 push-ups total.",
	"mission_data.b_3h_travail.title": "Mental Marathon",
	"mission_data.b_3h_travail.description": "Work or study for 3 hours without distraction.",
	"mission_data.b_8km.title": "Elite Endurance",
	"mission_data.b_8km.description": "Run 8 km.",
	"mission_data.b_agilite.title": "Agility",
	"mission_data.b_agilite.description": "Complete a full mobility session.",
	"mission_data.b_course.title": "Run",
	"mission_data.b_course.description": "Run 5 km.",
	"mission_data.b_groupe.title": "Leader's Influence",
	"mission_data.b_groupe.description": "Organize a group activity.",
	"mission_data.b_hebdo_depassement.title": "Breakthrough",
	"mission_data.b_hebdo_depassement.description": "Beat a personal running record.",
	"mission_data.b_hebdo_sagesse.title": "Path of Wisdom",
	"mission_data.b_hebdo_sagesse.description": "Meditate 45 minutes every day for a full week.",
	"mission_data.b_lever_6h.title": "Unbending Will",
	"mission_data.b_lever_6h.description": "Wake up before 6:00 for 5 days.",
	"mission_data.b_livre.title": "Strategist's Mind",
	"mission_data.b_livre.description": "Read and summarize a self-improvement or strategy book.",
	"mission_data.b_marche_obs.title": "Total Perception",
	"mission_data.b_marche_obs.description": "Go for a walk without your phone, observing only your surroundings.",
	"mission_data.b_mental.title": "Mental",
	"mission_data.b_mental.description": "Take a fully cold shower.",
	"mission_data.b_precision.title": "Precision",
	"mission_data.b_precision.description": "Practice an exercise requiring high focus and coordination for 45 minutes.",
	"mission_data.b_reflexes_combat.title": "Combat Instinct",
	"mission_data.b_reflexes_combat.description": "Do 30 minutes of reflex or coordination training.",
	"mission_data.b_respiration.title": "Breathing Protocol",
	"mission_data.b_respiration.description": "Complete three heart-coherence breathing sessions across the day.",
	"mission_data.b_volume.title": "Volume",
	"mission_data.b_volume.description": "Do a strength-training session or heavy sport session.",
	"mission_data.c_200_squats.title": "Body of Steel",
	"mission_data.c_200_squats.description": "Complete 200 squats total.",
	"mission_data.c_45min.title": "Continuous Chain",
	"mission_data.c_45min.description": "Train for 45 minutes without a long break.",
	"mission_data.c_5km.title": "Predator's Breath",
	"mission_data.c_5km.description": "Run 5 km without stopping.",
	"mission_data.c_activite.title": "Activity",
	"mission_data.c_activite.description": "Walk 10 km.",
	"mission_data.c_burpees.title": "Explosive Strength",
	"mission_data.c_burpees.description": "Do 20 burpees, then run 500 meters.",
	"mission_data.c_detox_sucre.title": "Reinforced Mind",
	"mission_data.c_detox_sucre.description": "Spend 24 hours without junk food or industrial sugar.",
	"mission_data.c_douche_froide.title": "Ice Immersion",
	"mission_data.c_douche_froide.description": "Take a fully cold shower for at least 5 minutes.",
	"mission_data.c_entrainement.title": "Training",
	"mission_data.c_entrainement.description": "Do an intense sport session.",
	"mission_data.c_foule.title": "Player's Eye",
	"mission_data.c_foule.description": "Observe a crowd and identify 10 different behaviors.",
	"mission_data.c_hebdo_savoir.title": "Assimilation",
	"mission_data.c_hebdo_savoir.description": "Finish a complex book or an online course.",
	"mission_data.c_hebdo_volonte.title": "Iron Will",
	"mission_data.c_hebdo_volonte.description": "Hold a strict routine for 7 days without deviation.",
	"mission_data.c_lecture.title": "Reading",
	"mission_data.c_lecture.description": "Read 30 pages or watch 3 educational videos.",
	"mission_data.c_meditation.title": "Deep Presence",
	"mission_data.c_meditation.description": "Meditate for 30 minutes without interruption, observing thoughts without attaching to them.",
	"mission_data.c_reaction.title": "Instant Reaction",
	"mission_data.c_reaction.description": "Do a 20-minute agility workout.",
	"mission_data.c_respiration.title": "Double Coherence",
	"mission_data.c_respiration.description": "Complete two heart-coherence breathing sessions during the day.",
	"mission_data.c_routine_matin.title": "Perfect Routine",
	"mission_data.c_routine_matin.description": "Follow a complete morning routine for 7 days.",
	"mission_data.c_social.title": "Connection",
	"mission_data.c_social.description": "Start a meaningful conversation and strengthen a social bond.",
	"mission_data.c_souplesse.title": "Flexibility",
	"mission_data.c_souplesse.description": "Do mobility work or stretching.",
	"mission_data.d_discipline_taches.title": "Iron Discipline",
	"mission_data.d_discipline_taches.description": "Complete every planned task for the day.",
	"mission_data.d_double_seance.title": "Double Training",
	"mission_data.d_double_seance.description": "Do two training sessions in the same day.",
	"mission_data.d_douche_froide.title": "Cold Baptism",
	"mission_data.d_douche_froide.description": "Finish your shower with 2 full minutes of cold water.",
	"mission_data.d_etude.title": "Study",
	"mission_data.d_etude.description": "Read 20 pages or watch 2 educational videos.",
	"mission_data.d_force.title": "Strength",
	"mission_data.d_force.description": "Complete a full sport session.",
	"mission_data.d_hebdo_resistance.title": "Resistance",
	"mission_data.d_hebdo_resistance.description": "Complete an unusually intense physical effort.",
	"mission_data.d_hebdo_savoir.title": "Knowledge Acquisition",
	"mission_data.d_hebdo_savoir.description": "Complete an online course or read an entire book during the week.",
	"mission_data.d_hiit.title": "Ghost Movement",
	"mission_data.d_hiit.description": "Do a 15-minute HIIT workout.",
	"mission_data.d_meditation.title": "Mindfulness",
	"mission_data.d_meditation.description": "Meditate for 20 minutes while focusing only on your breathing.",
	"mission_data.d_mouvement.title": "Movement",
	"mission_data.d_mouvement.description": "Walk 7 km.",
	"mission_data.d_parole.title": "Growing Presence",
	"mission_data.d_parole.description": "Speak in front of several people.",
	"mission_data.d_pas.title": "Continuous Load",
	"mission_data.d_pas.description": "Take 10000 steps during the day.",
	"mission_data.d_perception.title": "Terrain Reading",
	"mission_data.d_perception.description": "Find 5 shortcuts or optimizations in your daily routine.",
	"mission_data.d_respiration.title": "Heart Coherence",
	"mission_data.d_respiration.description": "Complete one heart-coherence session: 5 minutes, 5 breaths per minute.",
	"mission_data.d_soin.title": "Self-Care",
	"mission_data.d_soin.description": "Groom beard or body hair and improve your general style.",
	"mission_data.d_volonte_tache.title": "Sharpened Will",
	"mission_data.d_volonte_tache.description": "Finish an important task without interruption.",
	"mission_data.e_adaptation.title": "Fast Adaptation",
	"mission_data.e_adaptation.description": "Try a new physical activity.",
	"mission_data.e_apparence.title": "Appearance",
	"mission_data.e_apparence.description": "Shower, care for your face, and wear clean clothes.",
	"mission_data.e_apprentissage.title": "Learning",
	"mission_data.e_apprentissage.description": "Read 10 pages or watch educational content.",
	"mission_data.e_concentration.title": "Total Concentration",
	"mission_data.e_concentration.description": "Spend 1 hour without social media.",
	"mission_data.e_corde_sauter.title": "Combat Rhythm",
	"mission_data.e_corde_sauter.description": "Do 3 sets of jump rope for 1 minute each.",
	"mission_data.e_douche_froide.title": "Cold Endurance",
	"mission_data.e_douche_froide.description": "Finish your shower with 1 full minute of cold water.",
	"mission_data.e_endurance.title": "Endurance",
	"mission_data.e_endurance.description": "Walk 5 km.",
	"mission_data.e_hebdo_corps.title": "Fit Body",
	"mission_data.e_hebdo_corps.description": "Complete 5 sport sessions during the week.",
	"mission_data.e_hebdo_discipline.title": "Weekly Discipline",
	"mission_data.e_hebdo_discipline.description": "Hold your routine for the whole week.",
	"mission_data.e_impact.title": "Controlled Impact",
	"mission_data.e_impact.description": "Complete 100 squats total.",
	"mission_data.e_lecture.title": "Reading",
	"mission_data.e_lecture.description": "Read for 30 minutes without checking your phone.",
	"mission_data.e_meditation.title": "Inner Silence",
	"mission_data.e_meditation.description": "Meditate for 15 minutes while staying still and refocusing after each distraction.",
	"mission_data.e_respiration.title": "Expanded Breath",
	"mission_data.e_respiration.description": "Do 10 minutes of controlled breathing exercises.",
	"mission_data.e_sport.title": "Sport",
	"mission_data.e_sport.description": "Complete one training session.",
	"mission_data.e_vision.title": "Heightened Vision",
	"mission_data.e_vision.description": "Observe a place for 5 minutes and memorize every detail.",
	"mission_data.f_contact.title": "First Contact",
	"mission_data.f_contact.description": "Start a conversation with a new person.",
	"mission_data.f_discipline.title": "Discipline",
	"mission_data.f_discipline.description": "Go to class or work.",
	"mission_data.f_douche_froide.title": "Mental Barrier",
	"mission_data.f_douche_froide.description": "Take a cold shower for 30 seconds.",
	"mission_data.f_hebdo_fondation.title": "Foundation",
	"mission_data.f_hebdo_fondation.description": "Do one physical activity every day for 5 consecutive days.",
	"mission_data.f_hygiene.title": "Hygiene",
	"mission_data.f_hygiene.description": "Brush your teeth morning and night.",
	"mission_data.f_lecture_base.title": "Basic Concentration",
	"mission_data.f_lecture_base.description": "Read 10 pages of a book.",
	"mission_data.f_marche.title": "Walk",
	"mission_data.f_marche.description": "Travel 2 km.",
	"mission_data.f_meditation.title": "Meditation",
	"mission_data.f_meditation.description": "Sit in silence and observe your breathing for 10 minutes.",
	"mission_data.f_observation.title": "Player's Vision",
	"mission_data.f_observation.description": "Spot and memorize 10 objects in a public place.",
	"mission_data.f_rangement.title": "Stable Routine",
	"mission_data.f_rangement.description": "Fully tidy your workspace or bedroom.",
	"mission_data.f_reflexes.title": "Emerging Reflexes",
	"mission_data.f_reflexes.description": "Bounce a ball 50 times without dropping it.",
	"mission_data.f_respiration.title": "Stable Breathing",
	"mission_data.f_respiration.description": "Do 5 minutes of controlled breathing.",
	"mission_data.f_reveil.title": "Wake-Up",
	"mission_data.f_reveil.description": "Do 5 minutes of stretching or muscle activation.",
	"mission_data.f_squats.title": "Physical Activation",
	"mission_data.f_squats.description": "Do 20 squats.",
	"mission_data.s_20km.title": "Infinite Endurance",
	"mission_data.s_20km.description": "Walk or run 20 km in one day.",
	"mission_data.s_7j_intensif.title": "Ascendant Awakening",
	"mission_data.s_7j_intensif.description": "Complete 7 days of intensive training without giving up.",
	"mission_data.s_calme.title": "Calm",
	"mission_data.s_calme.description": "Meditate for 15 minutes.",
	"mission_data.s_coaching.title": "King's Presence",
	"mission_data.s_coaching.description": "Inspire or coach someone toward a concrete goal.",
	"mission_data.s_conscience.title": "Ultimate Instinct",
	"mission_data.s_conscience.description": "Spend a full day fully aware of your environment.",
	"mission_data.s_corps.title": "Body",
	"mission_data.s_corps.description": "Practice total mobility and body control.",
	"mission_data.s_defi_extreme.title": "Transcendent Body",
	"mission_data.s_defi_extreme.description": "Do an extreme physical challenge adapted to your level.",
	"mission_data.s_explosivite.title": "Explosiveness",
	"mission_data.s_explosivite.description": "Complete an athlete-level sport session.",
	"mission_data.s_focus.title": "Focus",
	"mission_data.s_focus.description": "Complete 3 heart-coherence breathing sessions.",
	"mission_data.s_habitudes_60j.title": "Absolute Discipline",
	"mission_data.s_habitudes_60j.description": "Respect all your important habits for 60 days.",
	"mission_data.s_hebdo_apotheose.title": "Apotheosis",
	"mission_data.s_hebdo_apotheose.description": "Reach and maintain flow state for a full day of intensive work.",
	"mission_data.s_hebdo_eveil.title": "Total Awakening",
	"mission_data.s_hebdo_eveil.description": "Have a perfect week on every front.",
	"mission_data.s_maitrise.title": "Mastery",
	"mission_data.s_maitrise.description": "Wake up before 7:30 for 7 days.",
	"mission_data.s_performance.title": "Performance",
	"mission_data.s_performance.description": "Do 1 hour of intense cardio.",
	"mission_data.s_plan_90j.title": "Ascendant Mind",
	"mission_data.s_plan_90j.description": "Create a complete 90-day self-improvement plan.",
	"mission_data.s_sans_confort.title": "Extreme Survival",
	"mission_data.s_sans_confort.description": "Spend a full day without useless comfort or distraction.",
	"mission_data.s_technique.title": "Absolute Precision",
	"mission_data.s_technique.description": "Do advanced technical training for 1 hour.",
}

const FR := {
	"tab.character": "Personnage",
	"tab.camp": "Campement",
	"tab.missions": "Missions",
	"tab.grimoire": "Grimoire",
	"tab.social": "Social",
	"tab.dungeon": "Donjon",
	"tab.shop": "Boutique",
	"tab.options": "Options",
	"vital.health": "SANTE",
	"vital.endurance": "ENDURANCE",
	"vital.level": "NIVEAU %d",
	"inventory.title": "INVENTAIRE",
	"option.language": "LANGUE",
	"option.english": "ANGLAIS",
	"option.french": "FRANCAIS",
	"option.audio": "AUDIO",
	"option.music": "MUSIQUE",
	"option.sfx": "EFFETS",
	"option.sound_on": "SON : ON",
	"option.sound_off": "SON : OFF",
	"option.debug_on": "Mode debug : ON",
	"option.debug_off": "Mode debug : OFF",
	"placeholder.dungeon_title": "DONJON",
	"placeholder.dungeon_safe": "Mode securite actif. Le panneau complet du donjon est temporairement desactive pour isoler le crash.",
	"mission.daily_timer": "Quotidien %s",
	"mission.weekly_timer": "Hebdo %s",
	"mission.daily_section": "MISSIONS QUOTIDIENNES",
	"mission.weekly_section": "MISSION HEBDOMADAIRE",
	"mission.exhausted": "Missions epuisees.",
	"mission.no_weekly": "Aucun defi cette semaine.",
	"mission.not_found": "MISSION INTROUVABLE",
	"mission.journal": "Journal",
	"mission.journal_only_cap": "Journal uniquement: limite quotidienne atteinte",
	"mission.missing": "Manque : %s",
	"mission.blocked": "BLOQUE",
	"mission.launch": "LANCER - %d END",
	"mission.note_placeholder": "Note courte",
	"mission.ready": "Pret a valider",
	"mission.remaining": "Reste : %s",
	"mission.validate": "VALIDER",
	"mission.abandon": "ABANDONNER",
	"mission.locked": "BLOQUE",
	"mission.validation": "Validation : %s",
	"mission.validation_note": "note",
	"mission.validation_status_ready": "Pret",
	"mission.validation_status_wait": "En cours",
	"mission.blocker.not_found": "Mission introuvable",
	"mission.blocker.not_started": "Mission non lancee",
	"mission.blocker.time": "Temps %s/%s",
	"mission.blocker.objective": "Objectif %d/%d %s",
	"mission.blocker.note": "Note requise",
	"mission.daily_quests": "Quetes quotidiennes %d/%d",
	"mission.history": "Serie %dj | OK %d | KO %d",
	"journal.today": "Aujourd'hui : %d OK / %d KO",
	"journal.empty": "Aucune mission terminee pour l'instant.",
	"popup.level": "Niveau %d",
	"popup.stat_points": "+ 3 Points de Stats disponibles !",
	"popup.close": "FERMER",
	"popup.continue": "CONTINUER",
	"popup.understood": "COMPRIS",
	"popup.mission_complete": "MISSION ACCOMPLIE !",
	"popup.mission_failed": "MISSION ECHOUEE",
	"popup.mission_injury": "Tu as ete blesse durant ta mission.",
	"popup.journal_only": "Journal uniquement",
	"popup.daily_limit": "Limite quotidienne atteinte",
	"popup.rename": "CHANGER DE PSEUDO",
	"popup.name_placeholder": "Ton pseudo...",
	"popup.cancel": "ANNULER",
	"popup.confirm": "CONFIRMER",
	"item.power": "Puissance : %d",
	"item.no_bonus": "Aucun bonus",
	"item.type.weapon": "Arme",
	"item.type.armor": "Armure",
	"item.type.legs": "Jambes",
	"item.type.feet": "Pieds",
	"item.type.accessory": "Accessoire",
	"item.rarity.common": "Commun",
	"item.rarity.rare": "Rare",
	"item.rarity.epic": "Epique",
	"item.rarity.legendary": "Legendaire",
	"item.rarity.mythic": "Mythique",
	"dungeon.rank_title": "%s - Rang %s",
	"dungeon.floor_status": "Etage %d / %d - %s",
	"dungeon.dead": "Expulse du donjon. Recuperation requise avant une nouvelle tentative.",
	"dungeon.completed": "Donjon termine. Tu peux recommencer depuis le dernier checkpoint.",
	"dungeon.entry_cost": "Cout d'entree: %d END. Le donjon utilise ton rang actuel et tes stats.",
	"dungeon.checkpoint": "Checkpoint: etage %d | Meilleur etage: %d | HP %d/%d | END %d/%d",
	"dungeon.floor_clear": "Etage nettoye.",
	"dungeon.no_enemy": "Aucun ennemi.",
	"dungeon.loot": "BUTIN %s",
	"dungeon.energy": "Energie: %d / 100",
	"dungeon.enter": "Entrer (%d END)",
	"dungeon.auto": "Echange auto",
	"dungeon.special": "Attaque speciale",
	"dungeon.heal": "Soin",
	"dungeon.shield": "Bouclier",
	"dungeon.next": "Monter a l'etage suivant",
	"dungeon.leave": "Sortir du donjon",
	"dungeon.phase.combat": "Combat",
	"dungeon.phase.event": "Evenement",
	"dungeon.phase.clear": "Etage nettoye",
	"dungeon.phase.dead": "Defaite",
	"dungeon.phase.completed": "Termine",
	"dungeon.phase.idle": "Repos",
	"time.day_short": "j",
	"mission.validation_time": "Temps %s/%s",
	"mission.validation_objective": "Objectif %s",
	"mission.validation_free": "Validation libre",
	"mission.amount_label.actions": "actions",
	"mission.amount_label.reps": "reps",
	"mission.amount_label.pas": "pas",
	"mission.amount_label.pages": "pages",
	"mission.amount_label.km": "km",
	"popup.level_up": "LEVEL UP !",
	"item.action.sell": "VENDRE  %d OR",
	"item.action.equip": "EQUIPER",
	"item.action.unequip": "DESEQUIPER",
	"tooltip.rename": "Renommer",
	"debug.reset_daily": "Reset Quotidien",
	"debug.reset_weekly": "Reset Hebdo",
	"debug.level_up": "+ Niveau",
	"debug.loot": "+ Loot",
	"debug.invincible_on": "Invincible : ON",
	"debug.invincible_off": "Invincible : OFF",
	"bestiary.monster.bat": "Chauve-souris",
	"bestiary.monster.mimic": "Mimic",
	"bestiary.monster.rat": "Rat",
	"bestiary.monster.slime": "Slime",
	"bestiary.monster.flying_eye": "Oeil volant",
	"bestiary.monster.goblin": "Gobelin",
	"bestiary.monster.mushroom": "Champignon",
	"bestiary.monster.skeleton": "Squelette",
	"bestiary.monster.rat_savage": "Rat sauvage",
	"bestiary.monster.golem_blue": "Golem bleu",
	"bestiary.monster.golem_orange": "Golem orange",
	"bestiary.monster.demon_sword": "Epee demoniaque",
	"bestiary.monster.minotaur": "Minotaure",
	"bestiary.monster.demon_slime": "Demon slime",
	"bestiary.monster.knight": "Chevalier",
	"bestiary.view_large": "Voir en grand",
	"dungeon.name.f": "Bois fendu",
	"dungeon.name.e": "Caves de rouille",
	"dungeon.name.d": "Cryptes affamees",
	"dungeon.name.c": "Tour des echos",
	"dungeon.name.b": "Fosse des rois",
	"dungeon.name.a": "Citadelle noire",
	"dungeon.name.s": "Abime final",
	"dungeon.unavailable_rank": "Rang indisponible.",
	"dungeon.not_enough_end": "END insuffisante pour entrer.",
	"dungeon.not_enough_hp": "HP insuffisants pour entrer.",
	"dungeon.enter_log": "Entree dans %s. Checkpoint etage %d.",
	"dungeon.log.special": "Attaque speciale: -%d HP ennemi.",
	"dungeon.log.heal": "Soin: +%d HP.",
	"dungeon.log.shield": "Bouclier actif pour 2 echanges.",
	"dungeon.log.altar_hp": "Autel: -%d HP, ATK temporaire augmentee.",
	"dungeon.log.altar_end": "Autel: -%d END, DEF temporaire augmentee.",
	"dungeon.log.altar_ignore": "Tu ignores l'autel.",
	"dungeon.log.merchant_buy": "Marchand: potion recue, +%d HP.",
	"dungeon.log.pass": "Tu passes ton chemin.",
	"dungeon.log.test_success": "Test %s reussi. Energie +25.",
	"dungeon.log.test_fail": "Test %s rate. Piege: -%d HP.",
	"dungeon.log.short_path": "Chemin court: -%d HP, un etage gagne.",
	"dungeon.log.long_path": "Chemin long: DEF temporaire +2.",
	"dungeon.log.leave": "Sortie du donjon. Retour au checkpoint.",
	"dungeon.log.spawn": "Etage %d: %s apparait.",
	"dungeon.log.crit": "Coup critique: -%d HP ennemi.",
	"dungeon.log.player_hit": "Tu frappes: -%d HP ennemi.",
	"dungeon.log.enemy_hit": "%s attaque: -%d HP.",
	"dungeon.log.checkpoint": "Checkpoint atteint: etage %d.",
	"dungeon.log.floor_clear": "Etage %d nettoye. Tu peux monter.",
	"dungeon.log.event": "Evenement: %s.",
	"dungeon.log.complete": "%s termine. Les 100 etages sont vaincus.",
	"dungeon.log.defeat": "Defaite. Retour au checkpoint etage %d.",
	"dungeon.log.loot": "Butin obtenu: %s.",
	"dungeon.inventory_full": "Inventaire plein. Butin perdu.",
	"dungeon.enemy_type.Brute": "Brute",
	"dungeon.enemy_type.Assassin": "Assassin",
	"dungeon.enemy_type.Mage": "Mage",
	"dungeon.enemy_base.0.0": "Rat de cave",
	"dungeon.enemy_base.0.1": "Chien errant",
	"dungeon.enemy_base.0.2": "Bandit maigre",
	"dungeon.enemy_base.1.0": "Goule rouillee",
	"dungeon.enemy_base.1.1": "Voleur d'os",
	"dungeon.enemy_base.1.2": "Mage de suie",
	"dungeon.enemy_base.2.0": "Sentinelle creuse",
	"dungeon.enemy_base.2.1": "Ombre vive",
	"dungeon.enemy_base.2.2": "Cultiste",
	"dungeon.enemy_base.3.0": "Chevalier fendu",
	"dungeon.enemy_base.3.1": "Lame muette",
	"dungeon.enemy_base.3.2": "Oracle sec",
	"dungeon.enemy_base.4.0": "Geant de fosse",
	"dungeon.enemy_base.4.1": "Traqueur royal",
	"dungeon.enemy_base.4.2": "Mage sanglant",
	"dungeon.enemy_base.5.0": "Champion noir",
	"dungeon.enemy_base.5.1": "Assassin d'elite",
	"dungeon.enemy_base.5.2": "Archimage brise",
	"dungeon.enemy_base.6.0": "Avatar du gouffre",
	"dungeon.enemy_base.6.1": "Main du vide",
	"dungeon.enemy_base.6.2": "Prophete final",
	"dungeon.event.altar.title": "Autel fissure",
	"dungeon.event.altar.text": "Une pierre froide reclame un prix avant le prochain etage.",
	"dungeon.event.altar.choice_hp": "Sacrifier HP pour ATK",
	"dungeon.event.altar.choice_end": "Sacrifier END pour DEF",
	"dungeon.event.altar.choice_ignore": "Ignorer",
	"dungeon.event.merchant.title": "Marchand cache",
	"dungeon.event.merchant.text": "Une silhouette propose une potion contre 8 END.",
	"dungeon.event.merchant.choice_buy": "Acheter la potion",
	"dungeon.event.merchant.choice_pass": "Passer",
	"dungeon.event.trap.title": "Couloir piege",
	"dungeon.event.trap.text": "Le sol craque. Il faut agir vite ou lire le mecanisme.",
	"dungeon.event.trap.choice_agi": "Esquiver avec AGI",
	"dungeon.event.trap.choice_int": "Analyser avec INT",
	"dungeon.event.dilemma.title": "Deux chemins",
	"dungeon.event.dilemma.text": "Un raccourci dangereux descend dans la roche. L'autre contourne lentement.",
	"dungeon.event.dilemma.choice_short": "Chemin court",
	"dungeon.event.dilemma.choice_long": "Chemin long",
}

func normalize_locale(locale: String) -> String:
	return locale if SUPPORTED_LOCALES.has(locale) else DEFAULT_LOCALE

func text(locale: String, key: String, args: Array = []) -> String:
	var table := EN if normalize_locale(locale) == "en" else FR
	var value := String(table.get(key, EN.get(key, key)))
	if args.is_empty():
		return value
	return value % args

func has_text(locale: String, key: String) -> bool:
	var table := EN if normalize_locale(locale) == "en" else FR
	return table.has(key)
